export const DUMMY_FORM_DATA = [
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Full Name",
    name: "name",
    placeholder: "Jon Snow",
    required: true,
    rowIndex: 0,
    type: "text",
    value: "",
    variant: "Input",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Email",
    name: "email",
    placeholder: "jon@snow.com",
    required: true,
    rowIndex: 0,
    type: "email",
    value: "",
    variant: "Input",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Phone",
    name: "phone",
    placeholder: "xxxxxxxxxx",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Phone",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Password",
    name: "password",
    placeholder: "Enter your password",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Password Input",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Description",
    name: "description",
    placeholder: "Tell me about yourself.",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Textarea",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Language",
    name: "language",
    placeholder: "Select Language",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Combobox",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Terms and Conditions",
    name: "tnc",
    placeholder: "Terms and Conditions",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Checkbox",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Upload File(s)",
    name: "image",
    placeholder: "Sample placeholder",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "File Input",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "OTP",
    name: "otp",
    placeholder: "OTP",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "OTP Input",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Frameworks",
    name: "frameworks",
    placeholder: "Select Frameworks",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Multi Select",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Select Email",
    name: "emails",
    placeholder: "Select an Email",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Select",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Price",
    name: "price",
    placeholder: "Adjust the price",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Slider",
    step: 2,
    max: 100,
    min: 0,
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Whitelabel",
    name: "whitelabel",
    placeholder: "Whitelabel",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Switch",
  },
  {
    checked: true,
    description: "",
    disabled: false,
    label: "Tags",
    name: "tags",
    placeholder: "Add Tags",
    required: true,
    rowIndex: 0,
    type: "",
    value: "",
    variant: "Tags Input",
  },
];
